# Generated by Django 5.1.1 on 2024-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_category', models.CharField(choices=[('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('SEN', 'Senior'), ('MAS', 'Master')], default='SEN', max_length=4)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
