# Generated by Django 5.1.1 on 2024-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_category',
            field=models.CharField(choices=[('U9', 'Under 9'), ('U11', 'Under 11'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('SEN', 'Senior'), ('MAS', 'Master')], default='SEN', max_length=4),
        ),
    ]
