# Generated by Django 5.1.1 on 2024-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_player_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_category',
            field=models.CharField(choices=[('U19', 'Under 19'), ('Open', 'Open')], max_length=100),
        ),
    ]
