# Generated by Django 5.1.1 on 2024-10-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_player_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age_category',
            field=models.CharField(choices=[('U9', 'Under 9'), ('U11', 'Under 11'), ('U13', 'Under 13'), ('U15', 'Under 15'), ('U17', 'Under 17'), ('U19', 'Under 19'), ('Open', 'Open')], max_length=100),
        ),
    ]
